module.exports = {
	"Reading": [
		"On the Road",
		"Pride and Prejudice",
		"Native Son",
		"Communist Manifesto",
		"The Prince",
		"War and Peace",
		"The Fault in our Stars",
		"Hamlet",
		"Gone with the Wind",
		"Outliers",
		"The World is Flat: A Brief History of the Twenty-first Century",
		"Huckleberry Finn",
		"The Great Gatsby",
		"There Eyes were Watching God",
		"The Bible",
		"The Quran",
		"Lord of the Rings",
		"The Old Man and the Sea",
		"As I Lay Dying",
		"Paradise Lost",
		"To Kill a Mockingbird",
		"The Hate U Give",
		"The Book Thief",
		"Kite Runner",
		"50 Shades of Grey",
		"Fahrenheit 451",
		"1984",
		"Brave New World"
	],
	"Music": [
		"Pink Floyd",
		"Rolling Stones",
		"AC/DC",
		"Guns and Roses",
		"One Republic",
		"Coldplay",
		"Arctic Monkeys",
		"Taylor Swift",
		"Madonna",
		"Tupac",
		"Kendrick Lamar",
		"The Beatles",
		"Elvis",
		"Greenday",
		"Nirvana",
		"Katy Perry",
		"Cage the Elephant",
		"Jonas Brothers",
		"Kanye West",
		"Post Malone",
		"Train",
		"Drake",
		"Snoop Dog",
		"Frank Sinatra",
		"Johnny Cash",
		"Beethoven",
		"Mozart",
		"Bach",
		"Tchaikovsky",
		"Hans Zimmer",
		"Richard Strauss",
		"Richard Wagner",
		"Michael Jackson",
		"Queen",
		"Elton John"
	],
	"Companies": [
		"Google",
		"Amazon",
		"Android",
		"Apple",
		"Facebook",
		"Walmart",
		"Tesla",
		"BMW",
		"Jeep",
		"Mercedes-Benz",
		"Ford",
		"Ferrari",
		"Bentley",
		"Lamborghini",
		"Supreme",
		"Gucci",
		"Louis Vuitton",
		"Nasa"

	],
	"Organizations": [
		"Boy Scouts",
		"Girl Scouts",
		"Church of Latter Day Saints",
		"Salvation Army",
		"Archdiocese of Boston"
	],
	"Restaurants": [
		"Applebees",
		"Five Guys",
		"In \'n out",
		"Sweet Green",
		"Starbucks",
		"McDonalds"
	],
	"Movies": [
		"Casablanca",
		"Godfather",
		"Goodfellas",
		"Maltese Falcon",
		"Pulp Fiction",
		"2001 a Space Odyssey",
		"Gone with the Wind",
		"Wizard of Oz",
		"Apocalypse Now",
		"Full Metal Jacket",
		"Patton",
		"Blade Runner",
		"Citizen Kane",
		"Captain America",
		"Iron Man",
		"Deadpool",
		"Dark Knight",
		"Watchmen",
		"Star Wars",

	],
	"TV": [
		"Game of Thrones",
		"Mad Men",
		"The Sopranos",
		"Golden Girls",
		"Gilmore Girls",
		"Stranger Things",
		"Brady Bunch",
		"MASH",
		"Seinfeld",
		"Friends",
		"The Office",
		"The Big Bang Theory",
		"Roseanne",
		"House",
		"Doctor Who",
		"Sherlock",
		"Frasier",
		"Fresh Prince of Bel-Air"
	],
	"Fitness": [
		"US Women's Soccer",
		"NBC Olympics",
		"PGA",
		"Wimbledon",
		"Manchester United",
		"FC Barcelona",
		"Liverpool",
		"Chelsea",
		"Packers",
		"49ers",
		"Redskins",
		"Patriots",
		"Cle Browns",
		"Det Lions",
		"Steelers",
		"Giants",
		"Atl Falcons",
		"Bal Ravens",
		"Seahawks",
		"Oak Raiders",
		"LA Rams",
		"Water Polo",
		"US Rowing",
		"Wash Nationals",
		"Wash Wizards",
		"Clippers",
		"Celtics",
		"OKC Thunder",
		"T Raptors"

	],
	"Media" : [
		"Fox",
		"Cnn",
		"Vox",
		"NYT",
		"WSJ",
		"WashPo",
		"New Yorker",
		"The Economist",
		"NBC",
		"BBC",
		"The Atlantic",
		"National Review",
		"The Guardian",
		"Daily Mail",
		"Telegraph",
		"Times Mag",
		"PopSci",
		"People Mag",
		"NPR",
		"The Onion"
	]

}